name: Deploy Prod

on:
  push:
    branches: [ main ]

jobs:
  build-publish-deploy:
    runs-on: ubuntu-latest

    env:
      TZ: 'Etc/GMT+3'
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
    - uses: actions/checkout@master

    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '20.x'

    - name: Install dependencies, build and test
      run: |
        npm install
        npm run build --if-present
        npm test

    - name: Docker Login - Docker Hub
      uses: Azure/docker-login@v1
      with:
        login-server: ${{ secrets.APP_DOCKER_REGISTRY }}
        username: ${{ secrets.APP_DOCKER_USERNAME }}
        password: ${{ secrets.APP_DOCKER_PASSWORD }}

    - name: Build and Push in Azure ACR
      run: |
        docker build . --file Dockerfile --tag ${{ secrets.APP_DOCKER_REGISTRY }}/${{ secrets.APP_DOCKER_IMAGE }}:latest
        docker push ${{ secrets.APP_DOCKER_REGISTRY }}/${{ secrets.APP_DOCKER_IMAGE }}:latest
